/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require("fs");
const path = require("path");
const { VodUploadClient, VodUploadRequest } = require("vod-node-sdk");

const root = path.resolve(__dirname, "..");
const envPath = path.join(root, "vod-upload.env.local");
const resultsPath = path.join(root, "vod-ai-upload-results.json");
const sqlPath = path.join(root, "supabase-ai-course-data.sql");

const collection = {
  courseId: 103,
  code: "AI",
  title: "汉字就这么简单",
  description: "按集购买或购买合集后观看全部内容。",
  price: 79.6,
  dir: "D:\\批量视频\\AI营销\\新建文件夹 (2)",
};

const episodeCourseStartId = 201;

function loadLocalEnv() {
  if (!fs.existsSync(envPath)) return;

  const content = fs.readFileSync(envPath, "utf8");
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index === -1) continue;
    const key = trimmed.slice(0, index).trim();
    const value = trimmed.slice(index + 1).trim();
    if (key && !process.env[key]) process.env[key] = value;
  }
}

function requireEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing ${name}. Put it in ${path.basename(envPath)}.`);
  }
  return value;
}

function getVideos(dir) {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.mp4$/i.test(entry.name))
    .map((entry, index) => ({
      episodeNumber: index + 1,
      title: path.basename(entry.name, path.extname(entry.name)),
      name: entry.name,
      fullPath: path.join(dir, entry.name),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, "zh-Hans-CN"));
}

function uploadOne(client, region, request) {
  return new Promise((resolve, reject) => {
    client.upload(region, request, (error, data) => {
      if (error) reject(error);
      else resolve(data);
    });
  });
}

function sqlString(value) {
  return String(value ?? "").replace(/'/g, "''");
}

function buildSql(result) {
  const firstUrl = result.episodes[0]?.mediaUrl || "";
  const lines = [
    "-- Generated by scripts/upload-ai-vod.cjs",
    "-- Run supabase-course-episodes.sql before this file.",
    "",
    "update public.courses",
    "set title = '一字千金——文字构形与书法造型Q1',",
    "    description = '一字千金——文字构形与书法造型Q1 付费视频合集，购买后可观看全部集数。'",
    "where id = 101;",
    "",
    "update public.courses",
    "set title = '一字千金——文字构形与书法造型Q2',",
    "    description = '一字千金——文字构形与书法造型Q2 付费视频合集，购买后可观看全部集数。'",
    "where id = 102;",
    "",
    `insert into public.courses (id, title, description, price, video_url, is_free_preview) values (${collection.courseId}, '${sqlString(collection.title)}', '${sqlString(collection.description)}', ${collection.price}, '${sqlString(firstUrl)}', false) on conflict (id) do update set title = excluded.title, description = excluded.description, price = excluded.price, video_url = excluded.video_url, is_free_preview = excluded.is_free_preview;`,
  ];

  for (const episode of result.episodes) {
    const episodeCourseId = episodeCourseStartId + episode.episodeNumber - 1;
    const title = `${collection.title}：${episode.title}`;

    lines.push(
      `insert into public.course_episodes (course_id, episode_number, title, video_url, vod_file_id) values (${collection.courseId}, ${episode.episodeNumber}, '${sqlString(episode.title)}', '${sqlString(episode.mediaUrl)}', '${sqlString(episode.fileId)}') on conflict (course_id, episode_number) do update set title = excluded.title, video_url = excluded.video_url, vod_file_id = excluded.vod_file_id;`
    );

    lines.push(
      `insert into public.courses (id, title, description, price, video_url, is_free_preview) values (${episodeCourseId}, '${sqlString(title)}', '单集付费课程。', 19.9, '${sqlString(episode.mediaUrl)}', false) on conflict (id) do update set title = excluded.title, description = excluded.description, price = excluded.price, video_url = excluded.video_url, is_free_preview = excluded.is_free_preview;`
    );

    lines.push(
      `insert into public.course_episodes (course_id, episode_number, title, video_url, vod_file_id) values (${episodeCourseId}, 1, '${sqlString(episode.title)}', '${sqlString(episode.mediaUrl)}', '${sqlString(episode.fileId)}') on conflict (course_id, episode_number) do update set title = excluded.title, video_url = excluded.video_url, vod_file_id = excluded.vod_file_id;`
    );
  }

  return `${lines.join("\n")}\n`;
}

async function main() {
  loadLocalEnv();

  const secretId = requireEnv("TENCENTCLOUD_SECRET_ID");
  const secretKey = requireEnv("TENCENTCLOUD_SECRET_KEY");
  const region = process.env.TENCENT_VOD_REGION || "ap-guangzhou";
  const storageRegion = process.env.TENCENT_VOD_STORAGE_REGION || "ap-guangzhou";

  if (!fs.existsSync(collection.dir)) {
    throw new Error(`Video folder does not exist: ${collection.dir}`);
  }

  const client = new VodUploadClient(secretId, secretKey);
  const result = fs.existsSync(resultsPath)
    ? JSON.parse(fs.readFileSync(resultsPath, "utf8"))
    : { ...collection, episodes: [] };

  for (const video of getVideos(collection.dir)) {
    const existing = result.episodes.find((item) => item.filePath === video.fullPath);
    if (existing?.fileId && existing?.mediaUrl) {
      console.log(`skip ${video.title}: ${existing.fileId}`);
      continue;
    }

    const req = new VodUploadRequest();
    req.MediaFilePath = video.fullPath;
    req.MediaName = `${collection.title} ${video.title}`;
    req.StorageRegion = storageRegion;

    console.log(`upload ${video.title}: ${video.fullPath}`);
    const data = await uploadOne(client, region, req);
    if (!data.FileId || !data.MediaUrl) {
      throw new Error(`Upload did not return FileId/MediaUrl: ${JSON.stringify(data)}`);
    }

    result.episodes.push({
      episodeNumber: video.episodeNumber,
      title: video.title,
      fileName: video.name,
      filePath: video.fullPath,
      fileId: data.FileId,
      mediaUrl: data.MediaUrl,
    });

    result.episodes.sort((a, b) => a.episodeNumber - b.episodeNumber);
    fs.writeFileSync(resultsPath, `${JSON.stringify(result, null, 2)}\n`, "utf8");
    fs.writeFileSync(sqlPath, buildSql(result), "utf8");
  }

  fs.writeFileSync(resultsPath, `${JSON.stringify(result, null, 2)}\n`, "utf8");
  fs.writeFileSync(sqlPath, buildSql(result), "utf8");
  console.log(`done: ${resultsPath}`);
  console.log(`sql: ${sqlPath}`);
}

main().catch((error) => {
  console.error(error.message || error);
  process.exit(1);
});
